FROM rohitggarg/ruby-dev

RUN apk --update add youtube-dl
RUN python /usr/lib/python2.7/site-packages/easy_install.py --upgrade youtube_dl

ENV GEM_HOME /opt/app/vendor/bundle/ruby/2.4.0/
WORKDIR /opt/app

ENV AIRBRAKE_KEY key
ENV AIRBRAKE_URL url
ENV REDIS_URL redis://
ENV JUKEBOX_ADMIN_SECRET mysupersecurepassword
ENV QUEUE file.downloader

COPY Gemfile /opt/app/Gemfile
RUN bundle install --without production

COPY . /opt/app

VOLUME /opt/app/songs
CMD ['rake', 'resque:work']
