FROM ruby:2.4

RUN apt-get update
RUN apt-get -y install youtube-dl

ENV GEM_HOME /opt/app/vendor/bundle/ruby/2.4.0/
WORKDIR /opt/app

ENV AIRBRAKE_KEY key
ENV AIRBRAKE_URL url
ENV REDIS_URL redis://
ENV JUKEBOX_ADMIN_SECRET mysupersecurepassword
ENV QUEUE file.downloader

COPY Gemfile /opt/app/Gemfile
RUN bundle install --without production

COPY . /opt/app

VOLUME /opt/app/songs
CMD ['rake', 'resque:work']
