development:
  servername: localhost
  download_queue: localhost
  song_format: mp3
  players:
    - localhost
production:
  servername: rg-jukebox.herokuapp.com
  download_queue: file.downloader
  song_format: mp3
  players:
    - jukebox.player